/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData lastfm = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData puzzle_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData infinity_outline = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_alphabet_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_numeric = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dribbble_circled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin_circled = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_alt_outline = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe_alt = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_sun = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drizzle = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_flash = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pipette = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_outline = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_outline = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie_outline = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flow_cross = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certificate_outline = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData certificate = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors_outline = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shovel = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sprout = IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
